title: My GitHub.io Blog
description: A collection of my Markdown articles
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
